Repository I-RoshanKumar/Beginner_Hactoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#3 Create Heap_sort.py
  Heap_sort.py
Labels: good first issue, hactoberfest2022, hactoberfest accepted

#5 Pattern Programs in Java
  Patterns_in_Java/BUTTERFLY_PATTERN.java
  Patterns_in_Java/CharacterPrint.java
  Patterns_in_Java/DIAMOND_Pyramid.java
  Patterns_in_Java/Floyd_s_Triangle.java
  Patterns_in_Java/Half_Pyramid.java
Labels: hactoberfest2022, hactoberfest accepted

#6 Created a tic tac game in python
  Tictac.py
Labels: hactoberfest2022, hactoberfest accepted

#7 Create Insertionsort.py
  Insertionsort.py
Labels: hactoberfest2022, hactoberfest accepted

#9 📦 NEW: search-an-element-in-a-sorted-and-pivoted-array
  C++ program/a.exe
  C++ program/search-an-element-in-a-sorted-and-pivoted-array.cpp
Labels: hactoberfest2022, hactoberfest accepted

#8 Created a Alarm clock using python
  Alarm.py
Labels: hactoberfest2022, hactoberfest accepted

#13 circular queue
  cq.cpp
Labels: good first issue, hactoberfest2022, hactoberfest accepted

#14 Infix_to_postfix.cpp
  ipost.cpp
Labels: hactoberfest2022, hactoberfest accepted

#19 Create calculator.py
  calculator.py
Labels: hactoberfest2022, hactoberfest accepted

#20 Added Rock Paper Scissors Audio Game
  Rock_Paper_Scissors_Audio_Game.py
  Speech_To_Text.py
  Text_To_Speech.py
Labels: hactoberfest2022, hactoberfest accepted

#24 Cpp code to check if a Number is palindrome or/not
  check_if_a_number_is_plaindrome.cpp
Labels: hactoberfest2022, hactoberfest accepted

#25 deploy chatbot python
  chatbot.py
Labels: hactoberfest2022, hactoberfest accepted, beginnerfriendly

#26 reverse string without affecting special char
  reverse.cpp
Labels: hactoberfest2022, hactoberfest accepted

#31 Infix_ to_ prefix.cpp
  C++ program/ipre.cpp
Labels: hactoberfest2022, hactoberfest accepted

#33 Face Detection
  Facial_Detection/.vscode/settings.json
  Facial_Detection/deepface.txt
  Facial_Detection/facialexp.py
  Facial_Detection/sample.jpg
Labels: hactoberfest2022, hactoberfest accepted

#30 Create digitalclock.py
  digitalclock.py
Labels: hactoberfest2022, hactoberfest accepted

#29 Bubble-sort in java
  bubble-sort.java
Labels: hactoberfest2022, hactoberfest accepted

#27 binary to decimal converter
  binarytodecimal.py
Labels: hactoberfest2022, hactoberfest accepted

#34 real-time currency convertor
  currency_convertor.py
Labels: hactoberfest2022, hactoberfest accepted

#35 sort an array in ascending order
  C++ program/ascending-array.cpp
Labels: hactoberfest2022, hactoberfest accepted

#38 Added CPP code to add two matrices.
  C++ program/Add_two_matrices.cpp
Labels: hactoberfest2022, hactoberfest accepted

#39 count set bits
  set bits.py
Labels: hactoberfest2022, hactoberfest accepted

#40 create envelope.cpp
  envelope.cpp
Labels: hactoberfest2022, hactoberfest accepted

#41 QR code generator
  QR code generator.py
  roman_to_decimal.py
Labels: hactoberfest2022, hactoberfest accepted

#43 Create linked-list.c
  linked-list.c
Labels: hactoberfest2022, hactoberfest accepted

#46 added dualrhombus.c
  dualrhombus.c
  envelope.c
Labels: hactoberfest2022, hactoberfest accepted

#44 javascript
  first-unique-character-in-a-string
Labels: hactoberfest2022, hactoberfest accepted

#47 Added Kadane's Algorithm
  C++ program/kadanes_algorithm.cpp
Labels: hactoberfest2022, hactoberfest accepted

#48 added 2 problems with solution
  C++ program/left_view_of_a_binary_tree.cpp
  C++ program/swap_the_values_of_two_variables.cpp
Labels: hactoberfest2022, hactoberfest accepted

#49 Data Structure In C
  Data Structure/Array/Stack.c
  Data Structure/Array/binarySearch.c
  Data Structure/Array/dynamicArray.c
  Data Structure/Array/dynamicMax.c
  Data Structure/Array/linearSearch.c
  Data Structure/Array/matrix.c
  Data Structure/Array/maxMin.c
  Data Structure/Array/reverse.c
  Data Structure/Array/reverseArrayUsingPointers.c
  Data Structure/Array/sort/bubbleSort.c
  Data Structure/Array/sort/heapSort.c
  Data Structure/Array/sort/insertionSort.c
  Data Structure/Array/sort/mergeSort.c
  Data Structure/Array/sort/quickSort.c
  Data Structure/Array/sort/selectionSort.c
  Data Structure/Array/swap.c
  Data Structure/LINKED LIST/Deletion.c
  Data Structure/LINKED LIST/DeletionGFG.c
  Data Structure/LINKED LIST/Insertion.c
  Data Structure/LINKED LIST/LinkedList.c
  Data Structure/LINKED LIST/Queue1.c
  Data Structure/LINKED LIST/Searching.c
  Data Structure/LINKED LIST/doublyLikedList.c
  Data Structure/LINKED LIST/doublyLinkedListInsertion.c
  Data Structure/LINKED LIST/hello.c
  Data Structure/LINKED LIST/insertionGFG.c
Labels: hactoberfest2022, hactoberfest accepted

#51 Create fibonacci.py
  fibonacci.py
Labels: hactoberfest2022, hactoberfest accepted

#60 Starpattern.py
  Pattern2.py
  Starpattern.py
Labels: hactoberfest2022, hactoberfest accepted

#55 Adding stack problem solution
  Data Structure/Stack/stack_SDE.py
Labels: hactoberfest2022, hactoberfest accepted

#82 Multiplying two matrices
  Multiplying two matrices
Labels: hactoberfest2022, hactoberfest accepted

#81 Create Guessing Number
  Guessing Number
Labels: hactoberfest2022, hactoberfest accepted

#52 add heap in data structure section
  Data Structure/heap/directheap.cpp
  Data Structure/heap/insert_heap.cpp
  Data Structure/heap/max_heap.cpp
  Data Structure/heap/min_heap.cpp
Labels: hactoberfest2022, hactoberfest accepted

#53 Create asteroid game.py
  asteroid game.py
Labels: hactoberfest2022, hactoberfest accepted

#54 Create Python Program to check Armstrong Number
  Python Program to check Armstrong Number
Labels: good first issue, hactoberfest2022, hactoberfest accepted

#80 Hey, I have added the solution of replace characters in string
  C++ program/replacechar.cpp
Labels: hactoberfest2022, hactoberfest accepted

#79 css analogue clock
  clock.html
Labels: hactoberfest2022, hactoberfest accepted

#78 Create Largest.java
  Largest.java
Labels: hactoberfest2022, hactoberfest accepted

#77 Operations on singly linked list
  C++ program/SLL.cpp
Labels: hactoberfest2022, hactoberfest accepted

#76 Postfix _evaluation.cpp
  C++ program/evalpost.cpp
Labels: hactoberfest2022, hactoberfest accepted

#75 Create Linked_List_Operations.py
  Data Structure/LINKED LIST/Linked_List_Operations.py
Labels: hactoberfest2022, hactoberfest accepted

#74 Added code for Armstrong number in java please merge it
  Armstrong.java
Labels: hactoberfest2022, hactoberfest accepted

#73 Added Guess the Number Game using python
  Guess _the_Number_Game.py
Labels: hactoberfest2022, hactoberfest accepted

#71 Create paddle ball game using pygame python.py
  paddle ball game using pygame python.py
Labels: good first issue, hactoberfest2022, hactoberfest accepted

#70 Create c++ program set bit.cpp
  c++ program  set bit.cpp
Labels: hactoberfest2022, hactoberfest accepted

#68 Create contactform.html
  contactform.html
Labels: hactoberfest2022, hactoberfest accepted

#56 Adding all singly linked list programs
  Data Structure/LINKED LIST/all_singly_linked_list.py
Labels: hactoberfest2022, hactoberfest accepted

#67 Ml pca
  ml-pca.py
Labels: hactoberfest2022, hactoberfest accepted

#66 Addition of 2 numbers using pointer in c++.
  C++ program/Addition of 2 number using pointer.cpp
Labels: hactoberfest2022, hactoberfest accepted

#65 Add files via upload
  convert file to pdf.py.rar
Labels: hactoberfest2022, hactoberfest accepted

#63 Add files via upload
  Currency Converter.py
Labels: hactoberfest2022, hactoberfest accepted

#62 Merge Sorting.c
  MergeSort.c
Labels: hactoberfest2022, hactoberfest accepted

#84 QR Code reader and Generator
  QR_Code_Generator.py
Labels: hactoberfest2022, hactoberfest accepted

#59 added a linked list operations in c
  linked list operations.c
Labels: hactoberfest2022, hactoberfest accepted

#50 BMI calculator
  BMI_calculator.py
  rock_paper_scissor.py
Labels: hactoberfest2022, hactoberfest accepted

#110 Virahanka numbers.cpp
  Virahanka numbers.cpp
Labels: hactoberfest2022, hactoberfest accepted

#111 circlewithc++.cpp
  circle.cpp
Labels: hactoberfest2022, hactoberfest accepted

#103 Create Vowel_consonant_count.java
  Vowel_consonant_count.java
Labels: hactoberfest2022, hactoberfest accepted

#102 passward.py
  passward_generator.py
Labels: hactoberfest2022, hactoberfest accepted

#101 Reverse Linked List in cpp
  Data Structure/LINKED LIST/ReverseLinkedList.cpp
Labels: hactoberfest2022, hactoberfest accepted

#100 add LRU cache (LeetCode) commented code #hacktoberfest
  C++ program/LRU_cache.cpp
Labels: hactoberfest2022, hactoberfest accepted

#99 NQueen.py
  NQueen.py
Labels: hactoberfest2022, hactoberfest accepted

#98 Create coinchangeproblem.cpp
  coinchangeproblem.cpp
Labels: hactoberfest2022, hactoberfest accepted

#97 Main
  Patterns_in_Java/editdistance.java
Labels: hactoberfest2022, hactoberfest accepted

#96 D
  C++ program/evalpre.cpp
Labels: hactoberfest2022, hactoberfest accepted

#94 Create BubbleSort.py
  BubbleSort.py
Labels: hactoberfest2022, hactoberfest accepted

#92 battery animation html csss
  battery_animation.html
Labels: hactoberfest2022, hactoberfest accepted

#91 slideshow html css
  mobile-app-html.html
  slideshow-html-css.html
Labels: hactoberfest2022, hactoberfest accepted

#90 table printing in c++
  C++ program/multiplication table in c++
Labels: hactoberfest2022, hactoberfest accepted

#87 Reverse Nodes in k-Group
  Data Structure/LINKED LIST/Reverse Nodes in k-Group.cpp
Labels: hactoberfest2022, hactoberfest accepted

#86 Binary Heap.cpp
  Data Structure/heap/Binary Heap.cpp
Labels: hactoberfest2022, hactoberfest accepted

#104 created Difference Of Sum And Product Of Digits
  DifferenceOfSumAndProductOfDigits.cpp
Labels: hactoberfest2022, hactoberfest accepted

#105 Cyclic sort in java
  Data Structure/Array/sort/CyclicSort.java
Labels: hactoberfest2022, hactoberfest accepted

#130 Create Prime number
  C++ program/Prime number
Labels: hactoberfest2022, hactoberfest accepted

#106 currency converter
  currency converter
Labels: hactoberfest2022, hactoberfest accepted

#129 Create m Coloring Problem.py
  m Coloring Problem.py
Labels: hactoberfest2022, hactoberfest accepted

#109 Added code for reversing the LinkedList using Python language
  Data Structure/LINKED LIST/ReverseLinkedList.py
  Data Structure/Stack/MonotonicStack.py
Labels: hactoberfest2022, hactoberfest accepted

#112 Counting vowels in a given string
  Count_Vowels.py
Labels: hactoberfest2022, hactoberfest accepted

#113 nQueenProblem.py
  nQueenProblem.py
Labels: hactoberfest2022, hactoberfest accepted

#114 sendEmail.py
  sendEmail.py
Labels: hactoberfest2022, hactoberfest accepted

#115 Create AgeCalculator.py
  AgeCalculator.py
Labels: hactoberfest2022, hactoberfest accepted

#116 Create Palindrome_String.java
  Palindrome_String.java
Labels: hactoberfest2022, hactoberfest accepted

#117 add factorial.js
  factorial.js
Labels: hactoberfest2022, hactoberfest accepted

#118 Updated readme
  README.md
Labels: hactoberfest2022, hactoberfest accepted

#119 Recursion Programs
  Data Structure/recursion/checkarraysort.cpp
  Data Structure/recursion/countnumpath.cpp
  Data Structure/recursion/first_lastofarr.cpp
  Data Structure/recursion/genallstring.cpp
  Data Structure/recursion/numpathinmaze.cpp
  Data Structure/recursion/powofnum.cpp
  Data Structure/recursion/printallnum.cpp
  Data Structure/recursion/printallper.cpp
  Data Structure/recursion/removealldubclicate.cpp
  Data Structure/recursion/rep_pi.cpp
  Data Structure/recursion/reversestring.cpp
  Data Structure/recursion/sumof_nums.cpp
  Data Structure/recursion/towerofhanoi.cpp
  Data Structure/recursion/xtoend.cpp
Labels: hactoberfest2022, hactoberfest accepted

#120 Create bubble sort
  bubble sort
Labels: hactoberfest2022, hactoberfest accepted

#121 Create Binary Tree
  Binary Tree
Labels: hactoberfest2022, hactoberfest accepted

#132 Create Leap year
  C++ program/Leap year
Labels: hactoberfest2022, hactoberfest accepted

#134 Create Program to print full pyramid using *.py
  Program to print full pyramid using *.py
Labels: hactoberfest2022, hactoberfest accepted

#122 hacktoberfest-2022
  C++ program/poi_dyn_str.cpp
Labels: hactoberfest2022, hactoberfest accepted

#123 Added palindrome pattern program
  palindPattern.py
Labels: hactoberfest2022, hactoberfest accepted

#124 Drum Kit
  Drum Kit/images/crash.png
  Drum Kit/images/kick.png
  Drum Kit/images/snare.png
  Drum Kit/images/tom1.png
  Drum Kit/images/tom2.png
  Drum Kit/images/tom3.png
  Drum Kit/images/tom4.png
  Drum Kit/index.html
  Drum Kit/jsscript.js
  Drum Kit/sounds/crash.mp3
  Drum Kit/sounds/kick-bass.mp3
  Drum Kit/sounds/snare.mp3
  Drum Kit/sounds/tom-1.mp3
  Drum Kit/sounds/tom-2.mp3
  Drum Kit/sounds/tom-3.mp3
  Drum Kit/sounds/tom-4.mp3
  Drum Kit/style.css
Labels: hactoberfest2022, hactoberfest accepted

#125 student-management-system.c
  student-management-system.c
Labels: hactoberfest2022, hactoberfest accepted

#126 star java code
  Patterns_in_Java/star.java
Labels: hactoberfest2022, hactoberfest accepted

#127 Create Duplicate.java
  Duplicate.java
Labels: hactoberfest2022, hactoberfest accepted

#128 Create Travelling Salesman Problem.py
  Travelling Salesman Problem.py
Labels: hactoberfest2022, hactoberfest accepted

#131 Create the sum of all the natural numbers from 1 to n.
  C++ program/the sum of all the natural numbers from 1 to n.
Labels: hactoberfest2022, hactoberfest accepted

#135 Selection sort in java
  Data Structure/Array/sort/SelectionSort.java
Labels: hactoberfest2022, hactoberfest accepted

#136 Added Code
  C++ program/Egyptian_Fraction.cpp
Labels: hactoberfest2022, hactoberfest accepted

#137 Program to find an armstrong number in python
  Armstrong.py
Labels: hactoberfest2022, hactoberfest accepted

#140 Ceiling program in java
  Ceilling.java
Labels: hactoberfest2022, hactoberfest accepted

#141 A book consists of chapters, sections, subsections
  C++ program/the book
Labels: hactoberfest2022, hactoberfest accepted

#142 graph
  Data Structure/Graph
Labels: hactoberfest2022, hactoberfest accepted

#144 Check Palindrome Number
  C++ program/Check Palindrome Number
Labels: hactoberfest2022, hactoberfest accepted

#146 shell sort
  shellsort.py
Labels: hactoberfest2022, hactoberfest accepted

#147 c++ code fixed
  C++ program/the sum of all the natural numbers from 1 to n.
Labels: hactoberfest2022, hactoberfest accepted

#149 Create insertion_Sort.cpp
  Data Structure/Array/sort/insertionsort.cpp
Labels: hactoberfest2022, hactoberfest accepted

#150 Find Subarray With Given Sum
  Find_Subarray_With_Given_Sum.py
Labels: good first issue, hactoberfest2022, hactoberfest accepted

#156 Zig-Zag Level Order Traversal cpp solution
  C++ program/Zig-Zag Level Order Traversal
Labels: good first issue, hactoberfest2022, hactoberfest accepted

#157 Add Matrix
  Add_matrix.py
Labels: hactoberfest2022, hactoberfest accepted

#158 Created circular single linked list algorithm using c language
  Data Structure/LINKED LIST/CircularSingleLinkedList.c
Labels: hactoberfest2022, hactoberfest accepted

#159 Create bubble_sort using cpp
  bubble_sort using cpp
Labels: hactoberfest2022, hactoberfest accepted

#160 added binary search algorithm written in java
  BinarySearch.java
Labels: hactoberfest2022, hactoberfest accepted

#161 Added a QR code generator
  QRGenerator.py
Labels: hactoberfest2022, hactoberfest accepted

#170 insertion
  04_insertion_end.cpp
Labels: hactoberfest2022, hactoberfest accepted

#171 del
  12_del_at_end_janny.c
Labels: hactoberfest2022, hactoberfest accepted

#162 Create knapsack
  C++ program/knapsack
Labels: hactoberfest2022, hactoberfest accepted

#163 added kruskal algorithm written in java
  KruskalAlgorithm.java
Labels: hactoberfest2022, hactoberfest accepted

#164 add code of reverse doubly linked list
  Data Structure/reverse doubly.eml
Labels: hactoberfest2022, hactoberfest accepted

#165 turtle race game
  turtle race.py
Labels: hactoberfest2022, hactoberfest accepted

#166 Binary knapsack (0 - 1 knapsack) problem
  Binaryknapsack.py
Labels: hactoberfest2022, hactoberfest accepted

#169 Stock sell and buy problem in cpp
  C++ program/11-Stock_Buy_And_Sell_Problem.cpp
  Left_rotate_of_an_array_by_d_digits.cpp
Labels: hactoberfest2022, hactoberfest accepted

#167 i want to add arduino codes in your repo
  OhmMeter.ino
  Smart street light.ino
  Smart_dustbin_arduino.ino
  two_wheel_motor_robot.ino
Labels: hactoberfest2022, hactoberfest accepted

#172 Generator of Fibonacci series program is added in C language!!
  FIBONACCI.c
Labels: hactoberfest2022, hactoberfest accepted

#173 Simon_Game
  Simon_Game/game.js
  Simon_Game/index.html
  Simon_Game/simon.txt
  Simon_Game/sounds/blue.mp3
  Simon_Game/sounds/green.mp3
  Simon_Game/sounds/red.mp3
  Simon_Game/sounds/yellow.mp3
  Simon_Game/style.css
Labels: hactoberfest2022, hactoberfest accepted

#174 Created Diatance2points.py
  Diatance2points.py
Labels: hactoberfest2022, hactoberfest accepted

#179 java file
  java.java
Labels: hactoberfest2022, hactoberfest accepted

#181 Add files via upload
  about.html
  animation.html
  contact.html
  index.html
  style.css
Labels: hactoberfest2022, hactoberfest accepted

#180 Text repetition N number.py
  Text repetition N number.py
Labels: hactoberfest2022, hactoberfest accepted

#215 Create countVowels.js
  javascript/countVowels.js
Labels: hactoberfest2022, hactoberfest accepted

#249 Created Jarvis.py
  Jarvis.py
Labels: beginnerfriendly
